# TODO 202: decide whether this is a docker-specific template for container-images, or if this can be used in a generic way

# Configuration template for Parallel Genetic Algorithms (PGA), used when creating a new PGA.
# For more information on valid YAML syntax, have a look at this documentation on symfony.com:
# https://symfony.com/doc/current/components/yaml/yaml_format.html

# TODO 204: implement island model
# Predefined models: "Master-Slave" (only model that is currently usable) and "Island".
# Declare custom models representing one generation cycle.
# Use "/" as separator and ensure first/last image being the runner, e.g., "RUN/SEL/CO/MUT/FE/RUN".
model: 'Master-Slave'


# List of inter-component services to use in the PGA, including their initial scaling.
# Those in uppercase are predefined default services.
services: {
  MSG: {name: 'rabbitMQ', image: 'rabbitmq:3.8-alpine', scaling: ''},
  DB: {name: 'redis', image: 'redis:6.0-alpine', scaling: ''},
}


# List of setup components, including their initial scaling.
# Those in uppercase are predefined default setup components.
setups: {
  RUN:  {name: 'runner', image: 'jluech/pga-cloud-runner', scaling: 1, messaging: 'generation'},
  INIT: {name: 'initializer', image: 'jluech/pga-cloud-initializer', scaling: 2, messaging: 'initializer'},
}


# List all images of operators involved, including their initial scaling and messaging access (e.g., queue name for rabbitMQ).
# Those in uppercase are predefined default operators.
operators: {
  SEL:  {name: 'selection', image: 'jluech/pga-cloud-selection', scaling: 1, messaging: 'selection'},
  CO:   {name: 'crossover', image: 'jluech/pga-cloud-crossover', scaling: 1, messaging: 'crossover'},
  MUT:  {name: 'mutation', image: 'jluech/pga-cloud-mutation', scaling: 1, messaging: 'mutation'},
  FE:   {name: 'fitness', image: 'jluech/pga-cloud-fitness', scaling: 3, messaging: 'fitness'},
}


# Settings for providing an initial population.
# Define your population only by the solution strings, like so:
# individuals:
# - "<solution string>"
population: {
  use_initial_population: False,
  population_file_path: ''
}


# Properties for PGA execution.
# Define at least the predefined ones (uppercase), but can also include custom properties for custom operators.
# You can set USE_INIT=True to ensure deployment of INITs even if not used for generating the initial population.
properties: {
  USE_INIT: False,
  MAX_GENERATIONS: 1500,
  MAX_UNIMPROVED_GENERATIONS: 300,
  MAX_TIME_SECONDS: 600,
  POPULATION_SIZE: 100,
  RANDOM_SEED: "",
  MUTATION_RATE: 0.3,
  CROSSOVER_RATE: 0.5,
  ELITISM_RATE: 0.05,
}


# Define here any custom file paths. Use the following scheme <unique_key>: '<file_path>'
# Do NOT use the key "population" for it will be used by the initial population file defined above.
# Also do NOT use the key "config", which will be used by this configuration file.
custom_files: {

}
